### ISSUE TITLE
Neural Net - NNEF Conversion using Python3

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#362]
NNEF conversion to NNIR Failure

* Sample 3 - [Classification with VGG16 NNEF Model](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/samples/model_compiler_samples#sample-3---classification-using-pre-trained-nnef-model) Failure

```
 python /opt/rocm/mivisionx/model_compiler/python/nnef_to_nnir.py vgg16 vgg16-nnir
reading NNEF model from vgg16...
Traceback (most recent call last):
  File "/opt/rocm/mivisionx/model_compiler/python/nnef_to_nnir.py", line 350, in <module>
    main()
  File "/opt/rocm/mivisionx/model_compiler/python/nnef_to_nnir.py", line 346, in main
    nnef2ir(inputFolder, outputFolder, node_type_append)
  File "/opt/rocm/mivisionx/model_compiler/python/nnef_to_nnir.py", line 327, in nnef2ir
    nnef_graph = nnef.load_graph(inputFolder)
  File "build/bdist.linux-x86_64/egg/nnef/__init__.py", line 55, in load_graph
  File "build/bdist.linux-x86_64/egg/nnef/binary.py", line 148, in read_tensor
  File "build/bdist.linux-x86_64/egg/nnef/binary.py", line 102, in _fromfile
AttributeError: 'file' object has no attribute 'seekable'
```

**Comment by kiritigowda** [comment]
@hansely can you look at this issue?

**Comment by hansely** [comment]
Verified that the corresponding model conversion passes inside the MIVisionx-ubuntu18.04:latest docker.

**Comment by kiritigowda** [comment]
@hansely any updates on this?

**Comment by hansely** [comment]
@kiritigowda  I filed an issue to NNEF. I am waiting for their repsponse.

**Comment by kiritigowda** [comment]
PR #380 - Adds new instructions to use Model Compiler with Python 3

**Comment by kiritigowda** [comment]
#326 address this issue
